### ISSUE TITLE
loggerx can't be used in latest flutter with flutter_localizations

### ISSUE THREAD

**Issue by TonyD-TuftAndPaw** [abobija/loggerx#2]
A pubspec with:
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  loggerx: ^2.0.0
```

Returns:
```
Resolving dependencies...
Note: intl is pinned to version 0.20.2 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because loggerx >=2.0.0 depends on intl ^0.19.0 and every version of flutter_localizations from sdk depends on intl 0.20.2, loggerx >=2.0.0 is incompatible with flutter_localizations from sdk.
So, because tuft_and_paw_app depends on both flutter_localizations from sdk and loggerx ^2.0.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on loggerx: flutter pub add loggerx:^0.0.1-dev.1
Failed to update packages.
Process finished with exit code 1
```

Downgrading to `loggerx:^0.0.1-dev.1` doesn't seem like a real solution.
